# Change these first
owner: kescherCode # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: "kescher.at"
    url: https://www.kescher.at
    icon: https://www.kescher.at/favicon-194x194.png
  - name: "kescherCloud"
    url: https://cloud.kescher.at/status.php
    icon: https://cloud.kescher.at/apps/theming/favicon
  - name: "kescherGit"
    url: https://git.kescher.at/api/v1/version
    icon: https://git.kescher.at/img/gitea-lg.png
  - name: "Magnetico"
    url: https://magnetico.kescher.at/api/v0.1/torrents/
    expectedStatusCodes:
      - 404
  - name: "Doggos backend - Woods Cross"
    url: https://doggos.kescher.at/wc-lazy-lounge.mjpg
    icon: https://www.kescher.at/favicon-194x194.png
    method: HEAD
  - name: "Doggos frontend"
    url: https://doggos.kescher.at
    icon: https://www.kescher.at/favicon-194x194.png
  - name: "Doggos BETA frontend"
    url: https://beta.doggos.kescher.at
    icon: https://www.kescher.at/favicon-194x194.png
  - name: "Doggos backend - Salt Lake"
    url: https://doggos.kescher.at/sl-small-dog-patio.mjpg
    icon: https://www.kescher.at/favicon-194x194.png
    method: HEAD
  - name: "Matrix"
    url: https://matrix.kescher.at
    icon: https://www.kescher.at/favicon-194x194.png
  - name: "arch4edu mirror https"
    url: https://arch4edu.mirror.kescher.at/lastupdate
  - name: "arch4edu mirror rsync"
    url: arch4edu.mirror.kescher.at
    port: 873
    check: "tcp-ping"
  - name: "arch mirror https"
    url: https://arch.mirror.kescher.at/lastupdate
  - name: "arch mirror rsync"
    url: arch.mirror.kescher.at
    port: 873
    check: "tcp-ping"
  - name: "Monero node"
    url: unova.kescher.at
    port: 18081
    check: "tcp-ping"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.kescher.at
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.kescher.at/android-chrome-192x192.png
  name: Status - kescher.at
  introTitle: "Status page for **[kescher.at](https://www.kescher.at)** and related services"
  introMessage: "This status page is powered by [Upptime](https://github.com/upptime/upptime)."
  navbar:
    - title: Status
      href: /
    - title: kescher.at
      href: https://www.kescher.at
    - title: Telegram
      href: https://t.me/kescherStatus
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Custom section
user-agent: okaymate
